//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ClubActivity = new HashSet<ClubActivity>();
            this.MemberActivity = new HashSet<MemberActivity>();
        }
    
        public int ActID { get; set; }
        public string ActName { get; set; }
        public int CategoryID { get; set; }
        public string ActIntroduction { get; set; }
        public Nullable<System.DateTime> ActStartDate { get; set; }
        public Nullable<System.DateTime> ActEndDate { get; set; }
        public string ActAddress { get; set; }
        public int MemberID { get; set; }
        public int StoreID { get; set; }
        public int ActNumber { get; set; }
        public string StatusID { get; set; }
        public byte[] ActPhoto { get; set; }
        public string ActPhotoName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Member Member { get; set; }
        public virtual Status Status { get; set; }
        public virtual Stores Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubActivity> ClubActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberActivity> MemberActivity { get; set; }
    }
}
