//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Club()
        {
            this.ClubActivity = new HashSet<ClubActivity>();
            this.MemberClub = new HashSet<MemberClub>();
        }
    
        public int ClubID { get; set; }
        public string ClubName { get; set; }
        public int CategoryID { get; set; }
        public string ClubIntroduction { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public byte[] ClubImage { get; set; }
        public string Clubimagename { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubActivity> ClubActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberClub> MemberClub { get; set; }
    }
}
