//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberActivityDetail
    {
        public int MemberActivityDetailID { get; set; }
        public int MemberActivityID { get; set; }
        public System.DateTime Date { get; set; }
        public string ActivityStatus { get; set; }
        public Nullable<int> ClubActivityID { get; set; }
    
        public virtual ClubActivity ClubActivity { get; set; }
        public virtual MemberActivity MemberActivity { get; set; }
        public virtual Status Status { get; set; }
    }
}
