//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Photo()
        {
            this.PhotoLike = new HashSet<PhotoLike>();
        }
    
        public byte[] Photo1 { get; set; }
        public string PhotoName { get; set; }
        public int PhotoID { get; set; }
        public string PhotoIntroduction { get; set; }
        public System.DateTime PhotoDate { get; set; }
        public int AlbumsID { get; set; }
        public string PhotoFileName { get; set; }
        public int PhotoCategoryID { get; set; }
    
        public virtual Albums Albums { get; set; }
        public virtual PhotoCategory PhotoCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoLike> PhotoLike { get; set; }
    }
}
