//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UNEntities : DbContext
    {
        public UNEntities()
            : base("name=UNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Albums> Albums { get; set; }
        public virtual DbSet<Authority> Authority { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryType> CategoryType { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<ClubActivity> ClubActivity { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberActivity> MemberActivity { get; set; }
        public virtual DbSet<MemberActivityDetail> MemberActivityDetail { get; set; }
        public virtual DbSet<MemberCategory> MemberCategory { get; set; }
        public virtual DbSet<MemberClub> MemberClub { get; set; }
        public virtual DbSet<MemberPairList> MemberPairList { get; set; }
        public virtual DbSet<MemberStatus> MemberStatus { get; set; }
        public virtual DbSet<Pair> Pair { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<PhotoCategory> PhotoCategory { get; set; }
        public virtual DbSet<PhotoLike> PhotoLike { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
    }
}
